# src/test/resources/extent.properties
extent.reporter.spark.start=true
extent.reporter.spark.out=target/ExtentReport/ExtentSpark.html

#Screenshot folder
screenshot.dir=screenshots/
screenshot.rel.path=../screenshots/

# Report Title & Name
extent.reporter.spark.config=src/main/resources/extent-config.xml
extent.reporter.spark.vieworder=dashboard,test,category,exception,author,device

basefolder.name=test-output/SparkReport
basefolder.datetimepattern=d-MMM-YY HH-mm-ss


# System Info
systeminfo.os=Windows
systeminfo.user=Pushpa Raj
systeminfo.build=QA Automation
systeminfo.AppName=OrangeHRM