status = error
name = Log4j2Config

# Log folder
property.basePath = logs

appenders = console, rolling

# ========================
# Console Appender
# ========================
appender.console.type = Console
appender.console.name = ConsoleAppender
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%d{HH:mm:ss}] %-5level %c{1} - %msg%n

# ========================
# Rolling File Appender
# ========================
appender.rolling.type = RollingFile
appender.rolling.name = FileAppender
appender.rolling.fileName = ${basePath}/automation.log
appender.rolling.filePattern = ${basePath}/automation-%d{yyyy-MM-dd}-%i.log.gz

appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = [%d{yyyy-MM-dd HH:mm:ss}] %-5level %c{1} - %msg%n

appender.rolling.policies.type = Policies

# Rotate daily
appender.rolling.policies.time.type = TimeBasedTriggeringPolicy
appender.rolling.policies.time.interval = 1

# Rotate based on size
appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size = 5MB

# Keep max 5 files
appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.max = 5

# ========================
# Root Logger
# ========================
rootLogger.level = info
rootLogger.appenderRefs = console, rolling
rootLogger.appenderRef.console.ref = ConsoleAppender
rootLogger.appenderRef.rolling.ref = FileAppender